// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/stashapp/stash/pkg/models"
	mock "github.com/stretchr/testify/mock"
)

// LocalizedTitleReaderWriter is an autogenerated mock type for the LocalizedTitleReaderWriter type
type LocalizedTitleReaderWriter struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, obj
func (_m *LocalizedTitleReaderWriter) Create(ctx context.Context, obj *models.LocalizedTitle) error {
	ret := _m.Called(ctx, obj)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.LocalizedTitle) error); ok {
		r0 = rf(ctx, obj)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Destroy provides a mock function with given fields: ctx, id
func (_m *LocalizedTitleReaderWriter) Destroy(ctx context.Context, id int) error {
	ret := _m.Called(ctx, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DestroyForObject provides a mock function with given fields: ctx, objectType, objectID
func (_m *LocalizedTitleReaderWriter) DestroyForObject(ctx context.Context, objectType models.LocalizedTitleObjectType, objectID int) error {
	ret := _m.Called(ctx, objectType, objectID)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, models.LocalizedTitleObjectType, int) error); ok {
		r0 = rf(ctx, objectType, objectID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Find provides a mock function with given fields: ctx, id
func (_m *LocalizedTitleReaderWriter) Find(ctx context.Context, id int) (*models.LocalizedTitle, error) {
	ret := _m.Called(ctx, id)

	var r0 *models.LocalizedTitle
	if rf, ok := ret.Get(0).(func(context.Context, int) *models.LocalizedTitle); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.LocalizedTitle)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindForObject provides a mock function with given fields: ctx, objectType, objectID
func (_m *LocalizedTitleReaderWriter) FindForObject(ctx context.Context, objectType models.LocalizedTitleObjectType, objectID int) ([]*models.LocalizedTitle, error) {
	ret := _m.Called(ctx, objectType, objectID)

	var r0 []*models.LocalizedTitle
	if rf, ok := ret.Get(0).(func(context.Context, models.LocalizedTitleObjectType, int) []*models.LocalizedTitle); ok {
		r0 = rf(ctx, objectType, objectID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.LocalizedTitle)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, models.LocalizedTitleObjectType, int) error); ok {
		r1 = rf(ctx, objectType, objectID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindForObjectLanguage provides a mock function with given fields: ctx, objectType, objectID, languageCode
func (_m *LocalizedTitleReaderWriter) FindForObjectLanguage(ctx context.Context, objectType models.LocalizedTitleObjectType, objectID int, languageCode string) (*models.LocalizedTitle, error) {
	ret := _m.Called(ctx, objectType, objectID, languageCode)

	var r0 *models.LocalizedTitle
	if rf, ok := ret.Get(0).(func(context.Context, models.LocalizedTitleObjectType, int, string) *models.LocalizedTitle); ok {
		r0 = rf(ctx, objectType, objectID, languageCode)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.LocalizedTitle)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, models.LocalizedTitleObjectType, int, string) error); ok {
		r1 = rf(ctx, objectType, objectID, languageCode)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindMany provides a mock function with given fields: ctx, ids, ignoreNotFound
func (_m *LocalizedTitleReaderWriter) FindMany(ctx context.Context, ids []int, ignoreNotFound bool) ([]*models.LocalizedTitle, error) {
	ret := _m.Called(ctx, ids, ignoreNotFound)

	var r0 []*models.LocalizedTitle
	if rf, ok := ret.Get(0).(func(context.Context, []int, bool) []*models.LocalizedTitle); ok {
		r0 = rf(ctx, ids, ignoreNotFound)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.LocalizedTitle)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, []int, bool) error); ok {
		r1 = rf(ctx, ids, ignoreNotFound)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, obj
func (_m *LocalizedTitleReaderWriter) Update(ctx context.Context, obj *models.LocalizedTitle) error {
	ret := _m.Called(ctx, obj)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.LocalizedTitle) error); ok {
		r0 = rf(ctx, obj)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Upsert provides a mock function with given fields: ctx, obj
func (_m *LocalizedTitleReaderWriter) Upsert(ctx context.Context, obj *models.LocalizedTitle) error {
	ret := _m.Called(ctx, obj)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.LocalizedTitle) error); ok {
		r0 = rf(ctx, obj)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
